### ISSUE TITLE
Unable to generate encoding

### ISSUE THREAD

**Issue by tiagosousagarcia** [ATNU/soundscapes-of-text#1]
The client seems to be unable to generate a new encoding (i.e., if you change the text excerpt, voice etc). Default one still works (i.e., if you press play instantly from the landing page) but nothing else.

Snooping with Chrome dev tools I get these errors on the console:

`main.6111ad88af7537153161.js:1 e {headers: t, status: 502, statusText: "Bad Gateway", url: "http://soundscapes.atnu.di-projects.net/generate?voice=Amy", ok: false, …}error: "<html>
↵<head><title>502 Bad Gateway</title></head>
↵<body bgcolor="white">
↵<center><h1>502 Bad Gateway</h1></center>
↵<hr><center>nginx/1.14.0 (Ubuntu)</center>
↵</body>
↵</html>
↵
↵
↵
↵
↵
↵
↵"headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure response for http://soundscapes.atnu.di-projects.net/generate?voice=Amy: 502 Bad Gateway"name: "HttpErrorResponse"ok: falsestatus: 502statusText: "Bad Gateway"url: "http://soundscapes.atnu.di-projects.net/generate?voice=Amy"__proto__: Object
(anonymous) @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e._error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e._error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e._error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e.notifyError @ main.6111ad88af7537153161.js:1
e._error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e._error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
e.error @ main.6111ad88af7537153161.js:1
u @ main.6111ad88af7537153161.js:1
e.invokeTask @ polyfills.716198f89897a99b775e.js:1
onInvokeTask @ main.6111ad88af7537153161.js:1
e.invokeTask @ polyfills.716198f89897a99b775e.js:1
t.runTask @ polyfills.716198f89897a99b775e.js:1
t.invokeTask @ polyfills.716198f89897a99b775e.js:1
_ @ polyfills.716198f89897a99b775e.js:1
m @ polyfills.716198f89897a99b775e.js:1
error (async)
j @ polyfills.716198f89897a99b775e.js:1
e.scheduleTask @ polyfills.716198f89897a99b775e.js:1
onScheduleTask @ polyfills.716198f89897a99b775e.js:1
e.scheduleTask @ polyfills.716198f89897a99b775e.js:1
t.scheduleTask @ polyfills.716198f89897a99b775e.js:1
t.scheduleEventTask @ polyfills.716198f89897a99b775e.js:1
(anonymous) @ polyfills.716198f89897a99b775e.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
t._trySubscribe @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
a @ main.6111ad88af7537153161.js:1
e._innerSub @ main.6111ad88af7537153161.js:1
e._tryNext @ main.6111ad88af7537153161.js:1
e._next @ main.6111ad88af7537153161.js:1
e.next @ main.6111ad88af7537153161.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
t._trySubscribe @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.call @ main.6111ad88af7537153161.js:1
t.subscribe @ main.6111ad88af7537153161.js:1
t.updatePlayerSource @ main.6111ad88af7537153161.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
handleEvent @ main.6111ad88af7537153161.js:1
handleEvent @ main.6111ad88af7537153161.js:1
Kr @ main.6111ad88af7537153161.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
(anonymous) @ main.6111ad88af7537153161.js:1
e.invokeTask @ polyfills.716198f89897a99b775e.js:1
onInvokeTask @ main.6111ad88af7537153161.js:1
e.invokeTask @ polyfills.716198f89897a99b775e.js:1
t.runTask @ polyfills.716198f89897a99b775e.js:1
t.invokeTask @ polyfills.716198f89897a99b775e.js:1
_ @ polyfills.716198f89897a99b775e.js:1
m @ polyfills.716198f89897a99b775e.js:1
main.6111ad88af7537153161.js:1 getEncoding failed: Http failure response for http://soundscapes.atnu.di-projects.net/generate?voice=Amy: 502 Bad Gateway
main.6111ad88af7537153161.js:1 URL []`

**Comment by markdturner** [comment]
The encoding is being generated, the mp3 appears in the S3 bucket. The error seems to be around streaming the audio back to the frontend

**Comment by markdturner** [comment]
The bug occurred due to a misconfiguration in the nginx web server config file. I've updated the file to fix the issue.
