### ISSUE TITLE
Don't seem to be able to change voice used.

### ISSUE THREAD

**Issue by jamescummings** [ATNU/soundscapes-of-text#3]
I don't seem to be able to get it to switch to one of the other voices? Am I just missing something? (If so maybe we need to label more?)

**Comment by tiagosousagarcia** [comment]
I think this and issue #2 seem to be linked to issue #1

**Comment by jamescummings** [comment]
Indeed they may all be the same underlying thing. I was sort of noting them down as issues so we remember to test everything when we think it is fixed. ;-)

**Comment by markdturner** [comment]
Fixed as part of #4. A new voice selection system is in place after version 2.0
